### ISSUE TITLE
version_iter: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by marcin-gryszkalis** [freebsd/pytoport#10]
breaks on any package, eg.:

$ pytoport /tmp/x requests

[-] Generating files for requests...
[-] Generating Makefile
PySocks has extra info: extra == 'socks'
pyOpenSSL has extra info: extra == 'security'
idna has extra info: extra == 'security'
cryptography has extra info: extra == 'security'
Traceback (most recent call last):
  File "/usr/local/bin/pytoport", line 11, in <module>
    load_entry_point('pytoport==0.4.1', 'console_scripts', 'pytoport')()
  File "/usr/local/lib/python3.5/site-packages/pytoport/__init__.py", line 319, in main
    generate_makefile(data, path, **user)
  File "/usr/local/lib/python3.5/site-packages/pytoport/__init__.py", line 202, in generate_makefile
    min_py = get_minimum(data)
  File "/usr/local/lib/python3.5/site-packages/pytoport/__init__.py", line 109, in get_minimum
    supported = list(version_iter(data))
  File "/usr/local/lib/python3.5/site-packages/pytoport/__init__.py", line 99, in version_iter
    raw = parts[2].split('.')
IndexError: tuple index out of range

**Comment by 0mp** [comment]
This is fixed now.
